branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
language: node_js
node_js:
  - 4
  - 5
  - 6
  - stable
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
addons:
    code_climate:
        repo_token: cd17849fce8d9273988b6229cd454514d56e69c7fb0463af09bf7b7ba342d8b7
after_script:
  - nyc report --reporter=text-lcov | codeclimate-test-reporter
